import '@/styles/reset.css'
import '@/styles/globals.css'
import '@/styles/responsive.css'
import '@/styles/text.css'

import { Mulish } from 'next/font/google'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'Fast Code Chat',
  description: 'Generated by cikencey',
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={mulish.className}>
        {children}
      </body>
    </html>
  )
}
